#!/bin/env bash

cyan='\033[1;32m'
red='\033[1;31m'
yellow='\033[0;33m'
none='\033[0m'

if [ $# -eq 0 ]
then
	echo -e "${red}Usage example: enum 10.10.10.10"
	exit
fi

# OS
$(which os) $1

$(which enum-ports) $1
ports=$(cat nmap/scheduler | cut -d '/' -f 1 | tr '\n' ',' | sed s/,$//)

$(which python3) $(which enum-scheduler) $1 "$ports"

echo -e "${cyan}==========( Done )=========="
echo -e "${none}"

exit
