#!/bin/bash
# Usage: enum-subdns nameserver.example 10.10.10.2

cyan='\033[1;32m'
red='\033[1;31m'
yellow='\033[0;33m'
none='\033[0m'

mkdir dns 2>/dev/null

touch ./dns/subdns
echo -e "${cyan}==========( SubDNS Recon )==========" | tee -a ./dns/subdns
echo -e "${red}dnsrecon -D /home/baguette/pentest/lists/SecLists/Discovery/DNS/subdomains-top1million-5000.txt -d $1 -n $2" | tee -a ./dns/subdns
echo -e "${yellow}"	2>&1 | tee -a ./dns/subdns
$(which dnsrecon) -D /home/baguette/pentest/lists/SecLists/Discovery/DNS/subdomains-top1million-5000.txt -d $1 -n $2 2>&1 | tee -a ./dns/subdns
echo -e "${none}" | tee -a ./dns/subdns


